# Generated by Django 4.0.6 on 2022-07-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_projecttype_alter_project_main_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttype',
            name='number_of_projects',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/project_pics/'),
        ),
    ]
