# Generated by Django 4.0.6 on 2022-07-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_projecttype_number_of_projects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='applied_knowledge',
            field=models.ManyToManyField(to='backend.knowledge'),
        ),
    ]
