# Generated by Django 4.0.6 on 2022-08-04 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_project_applied_knowledge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
