# Generated by Django 4.0.6 on 2022-07-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_spokenlanguage'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(default='Ghana', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='spoken_languages',
            field=models.ManyToManyField(to='backend.spokenlanguage'),
        ),
    ]
