# Generated by Django 4.0.6 on 2022-08-04 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_programming_languages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='carrier_summary',
            new_name='career_summary',
        ),
    ]
