# Generated by Django 4.0.6 on 2022-08-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_carrier_summary_user_career_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cv',
            field=models.FileField(blank=True, upload_to='uploads/cv/'),
        ),
    ]
