# Generated by Django 4.0.6 on 2022-08-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_social_icon'),
        ('accounts', '0006_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social',
            field=models.ManyToManyField(blank=True, to='backend.social'),
        ),
    ]
