# Generated by Django 4.0.6 on 2022-08-06 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_social'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='career_summary',
            new_name='about',
        ),
    ]
